return {
  {
    "williamboman/mason.nvim",
    opts = {
      ensure_installed = {
        "bash-language-server",
        "clang-format",
        "clangd",
        "cmake-language-server",
        "cmakelang",
        "cmakelint",
        "cpplint",
        "cpptools",
        "css-lsp",
        "cssmodules-language-server",
        "dart-debug-adapter",
        "emmet-language-server",
        "emmet-ls",
        "html-lsp",
        "htmlhint",
        "json-lsp",
        "lua-language-server",
        "prettier",
        "prettierd",
        "shfmt",
        "sonarlint-language-server",
        "stylelint",
        "stylua",
        "typescript-language-server",
      },
    },
  },
}
